In [1]:
pip install requests pandas

Requirement already satisfied: requests in c:\users\mukil\anaconda3\lib\site-packages (2.32.5)
Requirement already satisfied: pandas in c:\users\mukil\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\mukil\anaconda3\lib\site-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\mukil\anaconda3\lib\site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\mukil\anaconda3\lib\site-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\mukil\anaconda3\lib\site-packages (from requests) (2026.4.22)
Requirement already satisfied: numpy>=1.26.0 in c:\users\mukil\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\mukil\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\mukil\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\mukil\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\mukil\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
# Libraries required for the full pipeline
import requests # fetches data from the raw GitHub URL

In [3]:
import pandas as pd # converts JSON to DataFrame and exports to CSV

In [4]:
import json # parses and previews raw JSON structure

In [5]:
# Raw GitHub URL pointing to the uploaded JSON file
url = "https://raw.githubusercontent.com/LawKRT/synthetic-datasets/refs/heads/main/MOCK_DATA.json"
# Send HTTP GET request to the URL
response = requests.get(url)

In [6]:
# Confirm the request succeeded
print(f"Status Code: {response.status_code}")
print(f"Content-Type: {response.headers['Content-Type']}")

Status Code: 200
Content-Type: text/plain; charset=utf-8

In [7]:
# Deserialize the raw JSON content into a Python list of dicts
data = response.json()

In [8]:
# Preview the first record
print(f"Total records: {len(data)}") # Confirm how many records were returned
print(f"First record: {json.dumps(data[0], indent=2)}")

Total records: 100
First record: {
  "id": 1,
  "first_name": "Opaline",
  "last_name": "Gudeman",
  "email": "ogudeman0@bbc.co.uk",
  "country": "Venezuela",
  "salary": 76290,
  "department": "HR",
  "hire_date": "16/10/2025"
}

In [9]:
# Load the list of dictionaries directly into a pandas DataFrame
df = pd.DataFrame(data)

# Inspect structure
print(df.shape)        # (rows, columns)
print(df.dtypes)       # column data types
df.head()              # preview first 5 rows

(100, 8)
id             int64
first_name    object
last_name     object
email         object
country       object
salary         int64
department    object
hire_date     object
dtype: object

,id,first_name,last_name,email,country,salary,department,hire_date
0,1,Opaline,Gudeman,ogudeman0@bbc.co.uk,Venezuela,76290,HR,16/10/2025
1,2,Ulrike,Feore,ufeore1@netscape.com,Russia,37223,Sales,16/09/2025
2,3,Carlie,Gilbanks,cgilbanks2@youtube.com,Portugal,94613,Finance,24/04/2026
3,4,Warden,Simeoli,wsimeoli3@ucoz.ru,South Korea,35888,Operations,24/03/2026
4,5,Yvor,Garett,ygarett4@ask.com,Indonesia,117328,Operations,31/12/2025

In [10]:
# Check for nulls(missing values across all columns)
print(df.isnull().sum())

# Specify the exact format from my Mockaroo data (dd/mm/yyyy)
df['hire_date'] = pd.to_datetime(df['hire_date'], format='%d/%m/%Y')

# Confirm salary is numeric
df['salary'] = pd.to_numeric(df['salary'], errors='coerce')

# Confirm final data types
df.dtypes

id            0
first_name    0
last_name     0
email         0
country       0
salary        0
department    0
hire_date     0
dtype: int64

id                     int64
first_name            object
last_name             object
email                 object
country               object
salary                 int64
department            object
hire_date     datetime64[ns]
dtype: object

In [11]:
# Define the full output path
output_path = "mock_employees.csv"

# Save to CSV — index=False removes the auto-generated row numbers
df.to_csv(output_path, index=False)

print(f"CSV saved: {output_path}")
print(f"Rows written: {len(df)}")

CSV saved: mock_employees.csv
Rows written: 100

In [12]:
#verify the csv was created

verify = pd.read_csv("mock_employees.csv")
verify.head()

,id,first_name,last_name,email,country,salary,department,hire_date
0,1,Opaline,Gudeman,ogudeman0@bbc.co.uk,Venezuela,76290,HR,2025-10-16
1,2,Ulrike,Feore,ufeore1@netscape.com,Russia,37223,Sales,2025-09-16
2,3,Carlie,Gilbanks,cgilbanks2@youtube.com,Portugal,94613,Finance,2026-04-24
3,4,Warden,Simeoli,wsimeoli3@ucoz.ru,South Korea,35888,Operations,2026-03-24
4,5,Yvor,Garett,ygarett4@ask.com,Indonesia,117328,Operations,2025-12-31

In [13]:
# prints the exact full path where the file sits on my machine.
import os

print(os.path.abspath("mock_employees.csv"))

C:\Users\mukil\anaconda_projects\a4314a8f-16ea-4a4c-9975-d74356717024\mock_employees.csv

In [14]:
#to save it to a specific folder instead
output_path = r"C:\Users\mukil\Desktop\Student Files - Power Query Fundamentals\LUXDEV\Python\mock_employees.csv"

df.to_csv(output_path, index=False)

print(f"Saved to: {output_path}")

Saved to: C:\Users\mukil\Desktop\Student Files - Power Query Fundamentals\LUXDEV\Python\mock_employees.csv

── ── PART 3 ──────────────────────────────

In [15]:
import requests
import pandas as pd
import json

In [16]:
response = requests.get("https://dummyjson.com/products")
raw = response.json()

# Top-level keys
print(raw.keys())
print(f"Total products available: {raw['total']}")
print(f"Records in this response: {len(raw['products'])}")

# Structure of one product
print(json.dumps(raw['products'][0], indent=2))

dict_keys(['products', 'total', 'skip', 'limit'])
Total products available: 194
Records in this response: 30
{
  "id": 1,
  "title": "Essence Mascara Lash Princess",
  "description": "The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.",
  "category": "beauty",
  "price": 9.99,
  "discountPercentage": 10.48,
  "rating": 2.56,
  "stock": 99,
  "tags": [
    "beauty",
    "mascara"
  ],
  "brand": "Essence",
  "sku": "BEA-ESS-ESS-001",
  "weight": 4,
  "dimensions": {
    "width": 15.14,
    "height": 13.08,
    "depth": 22.99
  },
  "warrantyInformation": "1 week warranty",
  "shippingInformation": "Ships in 3-5 business days",
  "availabilityStatus": "In Stock",
  "reviews": [
    {
      "rating": 3,
      "comment": "Would not recommend!",
      "date": "2025-04-30T09:41:02.053Z",
      "reviewerName": "Eleanor Collins",
      "reviewerEmail": "eleanor.collins@x.dummyjson.com"
    },
    {
      "rating": 4,
      "comment": "Very satisfied!",
      "date": "2025-04-30T09:41:02.053Z",
      "reviewerName": "Lucas Gordon",
      "reviewerEmail": "lucas.gordon@x.dummyjson.com"
    },
    {
      "rating": 5,
      "comment": "Highly impressed!",
      "date": "2025-04-30T09:41:02.053Z",
      "reviewerName": "Eleanor Collins",
      "reviewerEmail": "eleanor.collins@x.dummyjson.com"
    }
  ],
  "returnPolicy": "No return policy",
  "minimumOrderQuantity": 48,
  "meta": {
    "createdAt": "2025-04-30T09:41:02.053Z",
    "updatedAt": "2025-04-30T09:41:02.053Z",
    "barcode": "5784719087687",
    "qrCode": "https://cdn.dummyjson.com/public/qr-code.png"
  },
  "images": [
    "https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/1.webp"
  ],
  "thumbnail": "https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/thumbnail.webp"
}

In [17]:
response = requests.get("https://dummyjson.com/carts")
raw = response.json()

print(raw.keys())
print(f"Total carts available: {raw['total']}")
print(f"Records in this response: {len(raw['carts'])}")

print(json.dumps(raw['carts'][0], indent=2))

dict_keys(['carts', 'total', 'skip', 'limit'])
Total carts available: 208
Records in this response: 30
{
  "id": 1,
  "products": [
    {
      "id": 162,
      "title": "Blue Frock",
      "price": 29.99,
      "quantity": 4,
      "total": 119.96,
      "discountPercentage": 12.13,
      "discountedTotal": 105.41,
      "thumbnail": "https://cdn.dummyjson.com/product-images/tops/blue-frock/thumbnail.webp"
    },
    {
      "id": 113,
      "title": "Generic Motorcycle",
      "price": 3999.99,
      "quantity": 3,
      "total": 11999.97,
      "discountPercentage": 12.1,
      "discountedTotal": 10547.97,
      "thumbnail": "https://cdn.dummyjson.com/product-images/motorcycle/generic-motorcycle/thumbnail.webp"
    },
    {
      "id": 122,
      "title": "iPhone 6",
      "price": 299.99,
      "quantity": 3,
      "total": 899.97,
      "discountPercentage": 6.69,
      "discountedTotal": 839.76,
      "thumbnail": "https://cdn.dummyjson.com/product-images/smartphones/iphone-6/thumbnail.webp"
    },
    {
      "id": 138,
      "title": "Baseball Ball",
      "price": 8.99,
      "quantity": 2,
      "total": 17.98,
      "discountPercentage": 1.71,
      "discountedTotal": 17.67,
      "thumbnail": "https://cdn.dummyjson.com/product-images/sports-accessories/baseball-ball/thumbnail.webp"
    }
  ],
  "total": 13037.88,
  "discountedTotal": 11510.81,
  "userId": 1,
  "totalProducts": 4,
  "totalQuantity": 12
}

In [18]:
# Default response returns 30 — use limit=0 to fetch all 194
response = requests.get("https://dummyjson.com/products?limit=0")

print(f"Status Code: {response.status_code}")

products_raw = response.json()['products']
print(f"Total products fetched: {len(products_raw)}")

Status Code: 200
Total products fetched: 194

In [19]:
# pd.json_normalize handles nested dicts (dimensions, meta) automatically
df_products = pd.json_normalize(products_raw)

# Drop columns that are lists (images, tags, reviews) — not useful in flat CSV
list_columns = [col for col in df_products.columns 
                if df_products[col].apply(lambda x: isinstance(x, list)).any()]

print(f"List-type columns dropped: {list_columns}")
df_products = df_products.drop(columns=list_columns)

print(f"\nShape: {df_products.shape}")
print(f"\nColumns retained:\n{df_products.columns.tolist()}")
df_products.head()

List-type columns dropped: ['tags', 'reviews', 'images']

Shape: (194, 24)

Columns retained:
['id', 'title', 'description', 'category', 'price', 'discountPercentage', 'rating', 'stock', 'brand', 'sku', 'weight', 'warrantyInformation', 'shippingInformation', 'availabilityStatus', 'returnPolicy', 'minimumOrderQuantity', 'thumbnail', 'dimensions.width', 'dimensions.height', 'dimensions.depth', 'meta.createdAt', 'meta.updatedAt', 'meta.barcode', 'meta.qrCode']

,id,title,description,category,price,discountPercentage,rating,stock,brand,sku,...,returnPolicy,minimumOrderQuantity,thumbnail,dimensions.width,dimensions.height,dimensions.depth,meta.createdAt,meta.updatedAt,meta.barcode,meta.qrCode
0,1,Essence Mascara Lash Princess,The Essence Mascara Lash Princess is a popular...,beauty,9.99,10.48,2.56,99,Essence,BEA-ESS-ESS-001,...,No return policy,48,https://cdn.dummyjson.com/product-images/beaut...,15.14,13.08,22.99,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,5784719087687,https://cdn.dummyjson.com/public/qr-code.png
1,2,Eyeshadow Palette with Mirror,The Eyeshadow Palette with Mirror offers a ver...,beauty,19.99,18.19,2.86,34,Glamour Beauty,BEA-GLA-EYE-002,...,7 days return policy,20,https://cdn.dummyjson.com/product-images/beaut...,9.26,22.47,27.67,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,9170275171413,https://cdn.dummyjson.com/public/qr-code.png
2,3,Powder Canister,The Powder Canister is a finely milled setting...,beauty,14.99,9.84,4.64,89,Velvet Touch,BEA-VEL-POW-003,...,No return policy,22,https://cdn.dummyjson.com/product-images/beaut...,29.27,27.93,20.59,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,8418883906837,https://cdn.dummyjson.com/public/qr-code.png
3,4,Red Lipstick,The Red Lipstick is a classic and bold choice ...,beauty,12.99,12.16,4.36,91,Chic Cosmetics,BEA-CHI-LIP-004,...,7 days return policy,40,https://cdn.dummyjson.com/product-images/beaut...,18.11,28.38,22.17,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,9467746727219,https://cdn.dummyjson.com/public/qr-code.png
4,5,Red Nail Polish,The Red Nail Polish offers a rich and glossy r...,beauty,8.99,11.44,4.32,79,Nail Couture,BEA-NAI-NAI-005,...,No return policy,22,https://cdn.dummyjson.com/product-images/beaut...,21.63,16.48,29.84,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,4063010628104,https://cdn.dummyjson.com/public/qr-code.png

In [20]:
# Fix data types
df_products['price']               = pd.to_numeric(df_products['price'], errors='coerce')
df_products['discountPercentage']  = pd.to_numeric(df_products['discountPercentage'], errors='coerce')
df_products['rating']              = pd.to_numeric(df_products['rating'], errors='coerce')
df_products['stock']               = pd.to_numeric(df_products['stock'], errors='coerce')

# Check nulls
print("Null counts:")
print(df_products.isnull().sum())

# Export
products_path = r"C:\Users\mukil\Desktop\Student Files - Power Query Fundamentals\LUXDEV\Python\dummyjson_products.csv"
df_products.to_csv(products_path, index=False)

print(f"\nProducts CSV saved: {products_path}")
print(f"Rows written: {len(df_products)}")

Null counts:
id                       0
title                    0
description              0
category                 0
price                    0
discountPercentage       0
rating                   0
stock                    0
brand                   92
sku                      0
weight                   0
warrantyInformation      0
shippingInformation      0
availabilityStatus       0
returnPolicy             0
minimumOrderQuantity     0
thumbnail                0
dimensions.width         0
dimensions.height        0
dimensions.depth         0
meta.createdAt           0
meta.updatedAt           0
meta.barcode             0
meta.qrCode              0
dtype: int64

Products CSV saved: C:\Users\mukil\Desktop\Student Files - Power Query Fundamentals\LUXDEV\Python\dummyjson_products.csv
Rows written: 194

In [21]:
response = requests.get("https://dummyjson.com/carts?limit=0")

print(f"Status Code: {response.status_code}")

carts_raw = response.json()['carts']
print(f"Total carts fetched: {len(carts_raw)}")

Status Code: 200
Total carts fetched: 208

In [22]:
# Extract cart-level fields only (exclude the nested products list)
cart_summary = []

for cart in carts_raw:
    cart_summary.append({
        "cart_id"          : cart['id'],
        "user_id"          : cart['userId'],
        "total_products"   : cart['totalProducts'],
        "total_quantity"   : cart['totalQuantity'],
        "total_price"      : cart['total'],
        "discounted_total" : cart['discountedTotal']
    })

df_carts = pd.DataFrame(cart_summary)

print(f"Shape: {df_carts.shape}")
df_carts.head()

Shape: (208, 6)

,cart_id,user_id,total_products,total_quantity,total_price,discounted_total
0,1,1,4,12,13037.88,11510.81
1,2,2,2,7,139.93,125.70
2,3,3,6,15,1794.85,1625.77
3,4,4,2,7,689.93,636.81
4,5,5,3,12,1467.88,1205.80

In [23]:
# Explode the nested products list so each item gets its own row
cart_items = []

for cart in carts_raw:
    for item in cart['products']:
        cart_items.append({
            "cart_id"            : cart['id'],
            "user_id"            : cart['userId'],
            "product_id"         : item['id'],
            "product_title"      : item['title'],
            "product_price"      : item['price'],
            "quantity"           : item['quantity'],
            "total_item_price"   : item['total'],
            "discount_percentage": item['discountPercentage'],
            "discounted_price"   : item['discountedTotal']
        })

df_cart_items = pd.DataFrame(cart_items)

print(f"Shape: {df_cart_items.shape}")
df_cart_items.head(10)

Shape: (800, 9)

,cart_id,user_id,product_id,product_title,product_price,quantity,total_item_price,discount_percentage,discounted_price
0,1,1,162,Blue Frock,29.99,4,119.96,12.13,105.41
1,1,1,113,Generic Motorcycle,3999.99,3,11999.97,12.10,10547.97
2,1,1,122,iPhone 6,299.99,3,899.97,6.69,839.76
3,1,1,138,Baseball Ball,8.99,2,17.98,1.71,17.67
4,2,2,86,Man Short Sleeve Shirt,19.99,5,99.95,6.83,93.12
5,2,2,104,Apple iPhone Charger,19.99,2,39.98,18.52,32.58
6,3,3,24,Fish Steak,14.99,1,14.99,4.23,14.36
7,3,3,123,iPhone 13 Pro,1099.99,1,1099.99,9.37,996.92
8,3,3,129,Realme X,299.99,1,299.99,6.95,279.14
9,3,3,86,Man Short Sleeve Shirt,19.99,5,99.95,6.83,93.12

In [24]:
base_path = r"C:\Users\mukil\Desktop\Student Files - Power Query Fundamentals\LUXDEV\Python"

# Cart summary — one row per cart
carts_path = base_path + r"\dummyjson_carts_summary.csv"
df_carts.to_csv(carts_path, index=False)
print(f"Carts summary saved: {carts_path}")
print(f"Rows: {len(df_carts)}")

# Cart items — one row per product per cart
items_path = base_path + r"\dummyjson_cart_items.csv"
df_cart_items.to_csv(items_path, index=False)
print(f"Cart items saved: {items_path}")
print(f"Rows: {len(df_cart_items)}")

Carts summary saved: C:\Users\mukil\Desktop\Student Files - Power Query Fundamentals\LUXDEV\Python\dummyjson_carts_summary.csv
Rows: 208
Cart items saved: C:\Users\mukil\Desktop\Student Files - Power Query Fundamentals\LUXDEV\Python\dummyjson_cart_items.csv
Rows: 800

In [25]:
base_path = r"C:\Users\mukil\Desktop\Student Files - Power Query Fundamentals\LUXDEV\Python"

files = {
    "Products"      : base_path + r"\dummyjson_products.csv",
    "Carts Summary" : base_path + r"\dummyjson_carts_summary.csv",
    "Cart Items"    : base_path + r"\dummyjson_cart_items.csv"
}

for name, path in files.items():
    df_check = pd.read_csv(path)
    print(f"{name}: {df_check.shape[0]} rows, {df_check.shape[1]} columns")

Products: 194 rows, 24 columns
Carts Summary: 208 rows, 6 columns
Cart Items: 800 rows, 9 columns